# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "rnmqtqaegqpbpytqawpg"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a table or view. Limits payload size for accidental or malicious requests.
max_rows = 1000

[auth]
enabled = true
# The base URL of the production app (keep localhost in allowed redirects for development).
site_url = "https://app.legaczguard.com"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = [
  "https://app.legaczguard.com/auth/callback",
  "https://app.legaczguard.com/api/auth/callback",
  "https://app.legaczguard.com/account",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/api/auth/callback"
]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 86400
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 30
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# Require email confirmation outside of development.
enable_confirmations = true

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = true
# Template for sending SMS messages.
template = "Your LegaczGuard verification code is {{ .Code }}"

[auth.external.apple]
enabled = true
client_id = "{{ env "SUPABASE_APPLE_CLIENT_ID" }}"
secret = "{{ env "SUPABASE_APPLE_CLIENT_SECRET" }}"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""

[auth.external.facebook]
enabled = true
client_id = "{{ env "SUPABASE_FACEBOOK_CLIENT_ID" }}"
secret = "{{ env "SUPABASE_FACEBOOK_CLIENT_SECRET" }}"

[auth.external.github]
enabled = true
client_id = "{{ env "SUPABASE_GITHUB_CLIENT_ID" }}"
secret = "{{ env "SUPABASE_GITHUB_CLIENT_SECRET" }}"

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.google]
enabled = true
client_id = "{{ env "SUPABASE_GOOGLE_CLIENT_ID" }}"
secret = "{{ env "SUPABASE_GOOGLE_CLIENT_SECRET" }}"

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.linkedin]
enabled = true
client_id = "{{ env "SUPABASE_LINKEDIN_CLIENT_ID" }}"
secret = "{{ env "SUPABASE_LINKEDIN_CLIENT_SECRET" }}"

[auth.external.notion]
enabled = false
client_id = ""
secret = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 17

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Defaults to transaction mode, which means connections are kept open until the current transaction
# is completed.
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 15
# Maximum number of client connections allowed.
max_client_conn = 100

[analytics]
enabled = false
port = 54327
vector_port = 54328

[inbucket]
enabled = true
# Port to use for the Inbucket URL.
port = 54326

[storage]
enabled = true
# The maximum file size allowed for uploads.
file_size_limit = "200MiB"
# Disable object size validation for resumable uploads. Accepts "true"/"false". Default "false".
skip_size_validations = false
# Cache control headers for public buckets.
default_cache_control = "max-age=86400, public"

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv4)
ip_version = "IPv4"

[studio]
enabled = true
# Port to use for the Studio URL.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost:54321"
