version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      testing:
        patterns:
          - "jest*"
          - "@types/jest"
          - "ts-jest"
      supabase:
        patterns:
          - "@supabase/*"
