openapi: 3.0.3
info:
  title: Email Template API
  description: API for managing email templates
  version: 1.0.0
  contact:
    name: LegacyGuard Development Team

servers:
  - url: /api/email-templates
    description: Email template API

paths:
  /templates:
    get:
      summary: List email templates
      parameters:
        - name: category
          in: query
          schema:
            type: string
            enum: [welcome, notification, alert, transactional]
        - name: language
          in: query
          schema:
            type: string
            default: en
        - name: active
          in: query
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: List of email templates
          content:
            application/json:
              schema:
                type: object
                properties:
                  templates:
                    type: array
                    items:
                      $ref: '#/components/schemas/EmailTemplate'

    post:
      summary: Create email template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailTemplateInput'
      responses:
        '201':
          description: Template created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailTemplate'

  /templates/{id}:
    get:
      summary: Get email template
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Email template details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailTemplate'

    put:
      summary: Update email template
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailTemplateInput'
      responses:
        '200':
          description: Template updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailTemplate'

    delete:
      summary: Delete email template
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Template deleted

  /templates/{id}/render:
    post:
      summary: Render email template
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                variables:
                  type: object
                  description: Template variables for rendering
      responses:
        '200':
          description: Rendered email content
          content:
            application/json:
              schema:
                type: object
                properties:
                  subject:
                    type: string
                  html:
                    type: string
                  text:
                    type: string

components:
  schemas:
    EmailTemplate:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        subject:
          type: string
        htmlContent:
          type: string
        textContent:
          type: string
        variables:
          type: array
          items:
            type: string
        category:
          type: string
          enum: [welcome, notification, alert, transactional]
        language:
          type: string
        isActive:
          type: boolean
        version:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    EmailTemplateInput:
      type: object
      required:
        - name
        - subject
        - category
      properties:
        name:
          type: string
        subject:
          type: string
        htmlContent:
          type: string
        textContent:
          type: string
        variables:
          type: array
          items:
            type: string
        category:
          type: string
          enum: [welcome, notification, alert, transactional]
        language:
          type: string
        isActive:
          type: boolean