openapi: 3.0.3
info:
  title: Delivery Tracking API
  description: API for tracking email delivery status and analytics
  version: 1.0.0
  contact:
    name: LegacyGuard Development Team

servers:
  - url: /api/email-delivery
    description: Delivery tracking API

paths:
  /deliveries:
    get:
      summary: List email deliveries
      parameters:
        - name: userId
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum: [queued, sent, delivered, bounced, complained, failed]
        - name: templateId
          in: query
          schema:
            type: string
        - name: startDate
          in: query
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          schema:
            type: string
            format: date-time
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: List of email deliveries
          content:
            application/json:
              schema:
                type: object
                properties:
                  deliveries:
                    type: array
                    items:
                      $ref: '#/components/schemas/EmailDelivery'
                  total:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer

  /deliveries/{id}:
    get:
      summary: Get email delivery details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Email delivery details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailDelivery'
        '404':
          description: Delivery not found

  /deliveries/{id}/logs:
    get:
      summary: Get delivery logs
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Delivery log events
          content:
            application/json:
              schema:
                type: object
                properties:
                  logs:
                    type: array
                    items:
                      $ref: '#/components/schemas/EmailLog'

  /analytics/delivery:
    get:
      summary: Get delivery analytics
      parameters:
        - name: startDate
          in: query
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          schema:
            type: string
            format: date-time
        - name: groupBy
          in: query
          schema:
            type: string
            enum: [day, week, month]
            default: day
      responses:
        '200':
          description: Delivery analytics data
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalSent:
                    type: integer
                  totalDelivered:
                    type: integer
                  totalBounced:
                    type: integer
                  deliveryRate:
                    type: number
                  averageDeliveryTime:
                    type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                        sent:
                          type: integer
                        delivered:
                          type: integer
                        bounced:
                          type: integer

  /analytics/templates:
    get:
      summary: Get template performance analytics
      parameters:
        - name: startDate
          in: query
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Template performance data
          content:
            application/json:
              schema:
                type: object
                properties:
                  templates:
                    type: array
                    items:
                      type: object
                      properties:
                        templateId:
                          type: string
                        templateName:
                          type: string
                        sent:
                          type: integer
                        delivered:
                          type: integer
                        deliveryRate:
                          type: number

components:
  schemas:
    EmailDelivery:
      type: object
      properties:
        id:
          type: string
        messageId:
          type: string
        templateId:
          type: string
        toEmail:
          type: string
        toName:
          type: string
        fromEmail:
          type: string
        subject:
          type: string
        status:
          type: string
          enum: [queued, sent, delivered, bounced, complained, failed]
        sentAt:
          type: string
          format: date-time
        deliveredAt:
          type: string
          format: date-time
        bouncedAt:
          type: string
          format: date-time
        errorMessage:
          type: string
        retryCount:
          type: integer
        userId:
          type: string
        metadata:
          type: object
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    EmailLog:
      type: object
      properties:
        id:
          type: string
        deliveryId:
          type: string
        eventType:
          type: string
          enum: [sent, delivered, bounced, complained, opened, clicked]
        timestamp:
          type: string
          format: date-time
        details:
          type: object
        ipAddress:
          type: string
        userAgent:
          type: string
        metadata:
          type: object