openapi: 3.0.3
info:
  title: Journey Analytics API
  version: 1.0.0
  description: API for journey analytics and reporting

servers:
  - url: https://api.schwalbe.com/v1
    description: Production server

security:
  - bearerAuth: []

paths:
  /analytics/journeys:
    get:
      summary: Get aggregated journey metrics
      operationId: getJourneyAnalytics
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: date
        - name: dateTo
          in: query
          schema:
            type: string
            format: date
        - name: journeyType
          in: query
          schema:
            type: string
            enum: [consumer, professional, partner]
        - name: stage
          in: query
          schema:
            type: string
        - name: userSegment
          in: query
          schema:
            type: string
        - name: deviceType
          in: query
          schema:
            type: string
        - name: experimentId
          in: query
          schema:
            type: string
            format: uuid
        - name: metrics
          in: query
          schema:
            type: array
            items:
              type: string
              enum: [completion_rate, time_spent, touchpoint_count, satisfaction_score, drop_off_rate, conversion_rate]
      responses:
        '200':
          description: Journey analytics
          content:
            application/json:
              schema:
                type: object
                properties:
                  dateRange:
                    type: object
                    properties:
                      from:
                        type: string
                        format: date
                      to:
                        type: string
                        format: date
                  totalJourneys:
                    type: integer
                  activeJourneys:
                    type: integer
                  completedJourneys:
                    type: integer
                  metrics:
                    type: object
                    properties:
                      averageCompletionRate:
                        type: number
                      averageTimeSpentMinutes:
                        type: number
                      averageTouchpointCount:
                        type: number
                      averageSatisfactionScore:
                        type: number
                      overallDropOffRate:
                        type: number
                      overallConversionRate:
                        type: number
                  breakdowns:
                    type: object
                    properties:
                      byJourneyType:
                        type: object
                        additionalProperties:
                          type: object
                      byStage:
                        type: object
                        additionalProperties:
                          type: object
                      byUserSegment:
                        type: object
                        additionalProperties:
                          type: object
                      byDeviceType:
                        type: object
                        additionalProperties:
                          type: object

  /analytics/touchpoints:
    get:
      summary: Get touchpoint analytics
      operationId: getTouchpointAnalytics
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: date
        - name: dateTo
          in: query
          schema:
            type: string
            format: date
        - name: touchpointType
          in: query
          schema:
            type: string
        - name: channel
          in: query
          schema:
            type: string
            enum: [web, mobile, email, api, support]
        - name: success
          in: query
          schema:
            type: boolean
      responses:
        '200':
          description: Touchpoint analytics
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalTouchpoints:
                    type: integer
                  successRate:
                    type: number
                  averageDurationSeconds:
                    type: number
                  touchpointTypes:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        count:
                          type: integer
                        successRate:
                          type: number
                        averageDuration:
                          type: number
                  channels:
                    type: object
                    additionalProperties:
                      type: integer
                  performanceMetrics:
                    type: object
                    properties:
                      p50Duration:
                        type: number
                      p95Duration:
                        type: number
                      p99Duration:
                        type: number

  /analytics/conversion:
    get:
      summary: Get conversion analytics
      operationId: getConversionAnalytics
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: date
        - name: dateTo
          in: query
          schema:
            type: string
            format: date
        - name: funnelType
          in: query
          schema:
            type: string
            enum: [awareness, consideration, purchase, retention, advocacy]
        - name: experimentId
          in: query
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Conversion analytics
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalVisitors:
                    type: integer
                  totalConversions:
                    type: integer
                  overallConversionRate:
                    type: number
                  averageTimeToConvertDays:
                    type: number
                  funnels:
                    type: array
                    items:
                      type: object
                      properties:
                        funnelId:
                          type: string
                          format: uuid
                        funnelName:
                          type: string
                        funnelType:
                          type: string
                        visitors:
                          type: integer
                        conversions:
                          type: integer
                        conversionRate:
                          type: number
                        stages:
                          type: array
                          items:
                            type: object
                            properties:
                              stageName:
                                type: string
                              visitors:
                                type: integer
                              conversions:
                                type: integer
                              conversionRate:
                                type: number
                              dropOffRate:
                                type: number

  /analytics/reports:
    post:
      summary: Generate custom analytics report
      operationId: generateAnalyticsReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - reportType
                - dateRange
              properties:
                reportType:
                  type: string
                  enum: [journey_performance, touchpoint_analysis, conversion_funnel, user_experience, experiment_results]
                dateRange:
                  type: object
                  required:
                    - from
                    - to
                  properties:
                    from:
                      type: string
                      format: date
                    to:
                      type: string
                      format: date
                filters:
                  type: object
                  properties:
                    journeyType:
                      type: string
                      enum: [consumer, professional, partner]
                    userSegment:
                      type: string
                    deviceType:
                      type: string
                    experimentId:
                      type: string
                      format: uuid
                metrics:
                  type: array
                  items:
                    type: string
                format:
                  type: string
                  enum: [json, csv, pdf]
                  default: json
                emailRecipients:
                  type: array
                  items:
                    type: string
                    format: email
      responses:
        '202':
          description: Report generation started
          content:
            application/json:
              schema:
                type: object
                properties:
                  reportId:
                    type: string
                    format: uuid
                  status:
                    type: string
                    enum: [queued, processing, completed, failed]
                  estimatedCompletionTime:
                    type: string
                    format: date-time
        '400':
          $ref: '#/components/responses/BadRequest'

    get:
      summary: List generated reports
      operationId: listAnalyticsReports
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [queued, processing, completed, failed]
        - name: reportType
          in: query
          schema:
            type: string
            enum: [journey_performance, touchpoint_analysis, conversion_funnel, user_experience, experiment_results]
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: List of reports
          content:
            application/json:
              schema:
                type: object
                properties:
                  reports:
                    type: array
                    items:
                      type: object
                      properties:
                        reportId:
                          type: string
                          format: uuid
                        reportType:
                          type: string
                        status:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
                        completedAt:
                          type: string
                          format: date-time
                        downloadUrl:
                          type: string
                  total:
                    type: integer

  /analytics/realtime:
    get:
      summary: Get real-time analytics data
      operationId: getRealtimeAnalytics
      parameters:
        - name: metrics
          in: query
          schema:
            type: array
            items:
              type: string
              enum: [active_journeys, active_users, current_conversion_rate, recent_touchpoints, system_health]
      responses:
        '200':
          description: Real-time analytics
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  activeJourneys:
                    type: integer
                  activeUsers:
                    type: integer
                  currentConversionRate:
                    type: number
                  recentTouchpoints:
                    type: integer
                  systemHealth:
                    type: object
                    properties:
                      status:
                        type: string
                        enum: [healthy, degraded, critical]
                      responseTimeMs:
                        type: number
                      errorRate:
                        type: number

components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              message:
                type: string
              details:
                type: object

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT