// Localized strings for outputs (UI in English except localized document copy)
// i18n baseline: en, cs, sk. App supports 34 langs; we scope MVP to these three.

import type { OutputLanguage } from './index'

export function strings(lang: OutputLanguage) {
  const L = dict[lang] ?? dict.en
  return L
}

const dict = {
  en: {
    defaultTitle: 'Last Will and Testament',
    subject: 'Will Document',
    headerAria: 'Document header',
    mainAria: 'Document main content',
    footerAria: 'Document footer',
    testator: 'Testator',
    jurisdiction: 'Jurisdiction',
    footerNote: 'Generated by the Will Engine. Verify legal compliance before signing.',

    // Handwriting
    hwTitle: 'Handwriting Template',
    jurCZ: 'Czech Republic',
    jurSK: 'Slovak Republic',
    promptTestator: 'Full legal name of the testator',
    promptAddress: 'Permanent address',
    promptBody: 'Write your will text clearly in your own handwriting:',
    date: 'Date and place',
    testatorSignature: 'Testator’s signature',
    signatureLine: 'Signature line',
    witnesses: 'Witnesses (names and signatures)',

    // Checklist
    checklistTitle: 'Notarization Checklist',
    beforeVisit: 'Before the visit',
    atVisit: 'During the visit',
    afterVisit: 'After the visit',
    disclaimer: 'This checklist is informational and not a substitute for legal advice.',
    checklistCZ: {
      before: [
        'Bring a valid ID (passport or national ID).',
        'Prepare a clean, final draft of the will.',
        'Confirm witness availability if required for your form.',
      ],
      at: [
        'Confirm your intent and capacity with the notary.',
        'Sign in the notary’s presence; ensure witness signatures if required.',
        'Pay the notarization fee and request a receipt.',
      ],
      after: [
        'Store the original in a secure place; consider a vault.',
        'Share copies only with trusted parties (executor, attorney).',
        'Record where the original is stored.',
      ],
    },
    checklistSK: {
      before: [
        'Bring a valid ID (passport or national ID).',
        'Prepare a clean, final draft of the will.',
        'Confirm witness availability if required for your form.',
      ],
      at: [
        'Confirm your intent and capacity with the notary.',
        'Sign in the notary’s presence; ensure witness signatures if required.',
        'Pay the notarization fee and request a receipt.',
      ],
      after: [
        'Store the original in a secure place; consider a vault.',
        'Share copies only with trusted parties (executor, attorney).',
        'Record where the original is stored.',
      ],
    },
  },
  cs: {
    defaultTitle: 'Poslední vůle a závěť',
    subject: 'Závěť',
    headerAria: 'Záhlaví dokumentu',
    mainAria: 'Hlavní obsah dokumentu',
    footerAria: 'Zápatí dokumentu',
    testator: 'Zůstavitel',
    jurisdiction: 'Jurisdikce',
    footerNote: 'Vygenerováno Will Engine. Před podpisem ověřte právní náležitosti.',

    // Handwriting
    hwTitle: 'Šablona pro vlastnoruční závěť',
    jurCZ: 'Česká republika',
    jurSK: 'Slovenská republika',
    promptTestator: 'Celé jméno zůstavitele',
    promptAddress: 'Trvalá adresa',
    promptBody: 'Napište text závěti vlastní rukou čitelně:',
    date: 'Datum a místo',
    testatorSignature: 'Podpis zůstavitele',
    signatureLine: 'Linka pro podpis',
    witnesses: 'Svědci (jména a podpisy)',

    // Checklist
    checklistTitle: 'Kontrolní seznam pro ověření podpisu u notáře',
    beforeVisit: 'Před návštěvou',
    atVisit: 'Během návštěvy',
    afterVisit: 'Po návštěvě',
    disclaimer: 'Tento seznam má pouze informativní charakter a nenahrazuje právní poradenství.',
    checklistCZ: {
      before: [
        'Vezměte si platný doklad totožnosti (občanský průkaz nebo pas).',
        'Připravte čistý finální návrh závěti.',
        'Ověřte dostupnost svědků, pokud je to pro vaši formu vyžadováno.',
      ],
      at: [
        'Potvrďte svou vůli a způsobilost u notáře.',
        'Podepište před notářem; zajistěte podpisy svědků, pokud jsou vyžadovány.',
        'Zaplaťte poplatek a vyžádejte si potvrzení.',
      ],
      after: [
        'Uložte originál na bezpečné místo; zvažte trezor.',
        'Sdílejte kopie pouze s důvěryhodnými osobami (vykonavatel, právník).',
        'Zaznamenejte, kde je originál uložen.',
      ],
    },
    checklistSK: {
      before: [
        'Vezměte si platný doklad totožnosti (občanský průkaz nebo pas).',
        'Připravte čistý finální návrh závěti.',
        'Ověřte dostupnost svědků, pokud je to pro vaši formu vyžadováno.',
      ],
      at: [
        'Potvrďte svou vůli a způsobilost u notáře.',
        'Podepište před notářem; zajistěte podpisy svědků, pokud jsou vyžadovány.',
        'Zaplaťte poplatek a vyžádejte si potvrzení.',
      ],
      after: [
        'Uložte originál na bezpečné místo; zvažte trezor.',
        'Sdílejte kopie pouze s důvěryhodnými osobami (vykonavatel, právník).',
        'Zaznamenejte, kde je originál uložen.',
      ],
    },
  },
  sk: {
    defaultTitle: 'Závet',
    subject: 'Závetný dokument',
    headerAria: 'Hlavička dokumentu',
    mainAria: 'Hlavný obsah dokumentu',
    footerAria: 'Päta dokumentu',
    testator: 'Zůstaviteľ',
    jurisdiction: 'Jurisdikcia',
    footerNote: 'Vygenerované Will Engine. Pred podpisom overte právne náležitosti.',

    // Handwriting
    hwTitle: 'Šablóna pre vlastnoručný závet',
    jurCZ: 'Česká republika',
    jurSK: 'Slovenská republika',
    promptTestator: 'Celé meno zůstaviteľa',
    promptAddress: 'Trvalá adresa',
    promptBody: 'Napíšte text závetu vlastnou rukou čitateľne:',
    date: 'Dátum a miesto',
    testatorSignature: 'Podpis zůstaviteľa',
    signatureLine: 'Čiara na podpis',
    witnesses: 'Svedkovia (mená a podpisy)',

    // Checklist
    checklistTitle: 'Kontrolný zoznam pre overenie podpisu u notára',
    beforeVisit: 'Pred návštevou',
    atVisit: 'Počas návštevy',
    afterVisit: 'Po návšteve',
    disclaimer: 'Tento zoznam je informatívny a nenahrádza právne poradenstvo.',
    checklistCZ: {
      before: [
        'Prineste si platný doklad totožnosti (občiansky preukaz alebo pas).',
        'Pripravte čistý finálny návrh závetu.',
        'Overte dostupnosť svedkov, ak je to pre vašu formu potrebné.',
      ],
      at: [
        'Potvrďte svoju vôľu a spôsobilosť u notára.',
        'Podpíšte v prítomnosti notára; zabezpečte podpisy svedkov, ak sú požadované.',
        'Zaplaťte poplatok a požiadajte o potvrdenie.',
      ],
      after: [
        'Uložte originál na bezpečné miesto; zvážte trezor.',
        'Zdieľajte kópie len s dôveryhodnými osobami (vykonávateľ, právnik).',
        'Zaznamenajte, kde je originál uložený.',
      ],
    },
    checklistSK: {
      before: [
        'Prineste si platný doklad totožnosti (občiansky preukaz alebo pas).',
        'Pripravte čistý finálny návrh závetu.',
        'Overte dostupnosť svedkov, ak je to pre vašu formu potrebné.',
      ],
      at: [
        'Potvrďte svoju vôľu a spôsobilosť u notára.',
        'Podpíšte v prítomnosti notára; zabezpečte podpisy svedkov, ak sú požadované.',
        'Zaplaťte poplatok a požiadajte o potvrdenie.',
      ],
      after: [
        'Uložte originál na bezpečné miesto; zvážte trezor.',
        'Zdieľajte kópie len s dôveryhodnými osobami (vykonávateľ, právnik).',
        'Zaznamenajte, kde je originál uložený.',
      ],
    },
  },
} as const