openapi: 3.0.3
info:
  title: Analytics Tracking API
  version: 1.0.0
  description: Analytics tracking API for user behavior and event collection

servers:
  - url: https://api.schwalbe.dev
    description: Production server
  - url: https://api-staging.schwalbe.dev
    description: Staging server

security:
  - bearerAuth: []

paths:
  /api/analytics/events:
    post:
      summary: Track user events
      description: Track custom user events and interactions
      operationId: trackEvent
      tags:
        - Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - eventType
              properties:
                eventType:
                  type: string
                  maxLength: 100
                  example: button_click
                eventData:
                  type: object
                  additionalProperties: true
                  example:
                    buttonId: submit_form
                    page: /contact
                sessionId:
                  type: string
                  example: session_12345
                pageUrl:
                  type: string
                  example: /dashboard
                referrer:
                  type: string
                  example: /login
      responses:
        '202':
          description: Event accepted for processing
        '400':
          description: Invalid event data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid event type

    get:
      summary: Query analytics events
      description: Query and retrieve analytics events with filtering
      operationId: queryEvents
      tags:
        - Events
      parameters:
        - name: eventType
          in: query
          schema:
            type: string
          example: page_view
        - name: startDate
          in: query
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          schema:
            type: string
            format: date-time
        - name: userId
          in: query
          schema:
            type: string
        - name: sessionId
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 100
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Analytics events data
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/AnalyticsEvent'
                  total:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer
        '400':
          description: Invalid query parameters

  /api/analytics/pageview:
    post:
      summary: Track page views
      description: Track user page view events
      operationId: trackPageView
      tags:
        - Page Views
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - path
              properties:
                path:
                  type: string
                  example: /dashboard
                title:
                  type: string
                  example: User Dashboard
                referrer:
                  type: string
                  example: /login
                sessionId:
                  type: string
                  example: session_12345
                duration:
                  type: integer
                  description: Time spent on page in milliseconds
                  example: 30000
      responses:
        '202':
          description: Page view tracked
        '400':
          description: Invalid page view data

  /api/analytics/user-action:
    post:
      summary: Track user actions
      description: Track specific user actions and interactions
      operationId: trackUserAction
      tags:
        - User Actions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - action
                - category
              properties:
                action:
                  type: string
                  example: click
                category:
                  type: string
                  example: navigation
                label:
                  type: string
                  example: main_menu
                value:
                  type: number
                  description: Optional numeric value
                  example: 1
                context:
                  type: object
                  additionalProperties: true
                  example:
                    elementId: nav-button
                    page: /dashboard
      responses:
        '202':
          description: User action tracked
        '400':
          description: Invalid user action data

  /api/analytics/summary:
    get:
      summary: Get analytics summary
      description: Get aggregated analytics summary for a date range
      operationId: getAnalyticsSummary
      tags:
        - Summary
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: groupBy
          in: query
          schema:
            type: string
            enum: [day, hour, event_type]
            default: day
      responses:
        '200':
          description: Analytics summary data
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: object
                    properties:
                      totalEvents:
                        type: integer
                      uniqueSessions:
                        type: integer
                      uniqueUsers:
                        type: integer
                      eventTypes:
                        type: object
                        additionalProperties:
                          type: integer
                      topPages:
                        type: object
                        additionalProperties:
                          type: integer
                      devices:
                        type: object
                        properties:
                          mobile:
                            type: integer
                          desktop:
                            type: integer
                          tablet:
                            type: integer
                      browsers:
                        type: object
                        additionalProperties:
                          type: integer
                      timeSeries:
                        type: array
                        items:
                          type: object
                          properties:
                            timestamp:
                              type: string
                              format: date-time
                            events:
                              type: integer
                            sessions:
                              type: integer
                  dateRange:
                    type: object
                    properties:
                      start:
                        type: string
                        format: date-time
                      end:
                        type: string
                        format: date-time
        '400':
          description: Invalid date range

  /api/analytics/user/{userId}:
    get:
      summary: Get user analytics
      description: Get analytics data for a specific user
      operationId: getUserAnalytics
      tags:
        - User Analytics
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          schema:
            type: string
            format: date-time
        - name: eventType
          in: query
          schema:
            type: string
      responses:
        '200':
          description: User analytics data
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  summary:
                    type: object
                    properties:
                      totalEvents:
                        type: integer
                      sessions:
                        type: integer
                      lastActivity:
                        type: string
                        format: date-time
                      topEventTypes:
                        type: array
                        items:
                          type: object
                          properties:
                            eventType:
                              type: string
                            count:
                              type: integer
                      topPages:
                        type: array
                        items:
                          type: object
                          properties:
                            page:
                              type: string
                            count:
                              type: integer
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/AnalyticsEvent'
        '403':
          description: Access denied to user data
        '404':
          description: User not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AnalyticsEvent:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        eventType:
          type: string
        eventData:
          type: object
          additionalProperties: true
        sessionId:
          type: string
        deviceInfo:
          $ref: '#/components/schemas/DeviceInfo'
        pageUrl:
          type: string
        referrer:
          type: string
        createdAt:
          type: string
          format: date-time

    DeviceInfo:
      type: object
      properties:
        platform:
          type: string
          example: MacIntel
        browser:
          type: string
          example: Chrome
        browserVersion:
          type: string
          example: 91.0.4472.124
        isMobile:
          type: boolean
          example: false
        screenWidth:
          type: integer
          example: 1920
        screenHeight:
          type: integer
          example: 1080
        viewportWidth:
          type: integer
          example: 1920
        viewportHeight:
          type: integer
          example: 1080
        language:
          type: string
          example: en-US
        timezone:
          type: string
          example: Europe/Prague

    PageViewEvent:
      type: object
      required:
        - path
      properties:
        path:
          type: string
        title:
          type: string
        referrer:
          type: string
        sessionId:
          type: string
        duration:
          type: integer

    UserActionEvent:
      type: object
      required:
        - action
        - category
      properties:
        action:
          type: string
        category:
          type: string
        label:
          type: string
        value:
          type: number
        context:
          type: object
          additionalProperties: true

    AnalyticsSummary:
      type: object
      properties:
        totalEvents:
          type: integer
        uniqueSessions:
          type: integer
        uniqueUsers:
          type: integer
        eventTypes:
          type: object
          additionalProperties:
            type: integer
        topPages:
          type: object
          additionalProperties:
            type: integer
        devices:
          type: object
          properties:
            mobile:
              type: integer
            desktop:
              type: integer
            tablet:
              type: integer
        browsers:
          type: object
          additionalProperties:
            type: integer
        timeSeries:
          type: array
          items:
            type: object
            properties:
              timestamp:
                type: string
                format: date-time
              events:
                type: integer
              sessions:
                type: integer

  responses:
    EventAccepted:
      description: Event accepted for processing
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: accepted
              eventId:
                type: string

    ValidationError:
      description: Invalid request data
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Validation failed
              details:
                type: array
                items:
                  type: string

    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unauthorized

    ForbiddenError:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Forbidden