name: e2e-money-path

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      # Base URL of staging app (e.g., https://staging.legacyguard.cz)
      E2E_BASE_URL: ${{ secrets.E2E_BASE_URL }}
      # Supabase project credentials (public anon key is fine but still treat as secret)
      E2E_SUPABASE_URL: ${{ secrets.E2E_SUPABASE_URL }}
      E2E_SUPABASE_ANON_KEY: ${{ secrets.E2E_SUPABASE_ANON_KEY }}
      # Test user credentials present in staging project (email/password)
      E2E_TEST_EMAIL: ${{ secrets.E2E_TEST_EMAIL }}
      E2E_TEST_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (repo)
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: apps/web
        run: npx playwright install --with-deps

      - name: Run E2E money-path smoke tests (staging)
        working-directory: apps/web
        run: npx playwright test -c ./playwright.config.ts --reporter=list,html --project=chromium

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report
          if-no-files-found: ignore

      - name: Upload test-results (traces/screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: apps/web/test-results
          if-no-files-found: ignore