name: Notify Trial Ending (Staging)

on:
  schedule:
    - cron: "0 9 * * *"  # 09:00 UTC daily, staging window
  workflow_dispatch: {}

jobs:
  run-notify-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase function notify-trial-ending (staging)
        env:
          SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.STAGING_SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
            echo "Missing staging secrets STAGING_SUPABASE_URL or STAGING_SUPABASE_SERVICE_ROLE_KEY" >&2
            exit 1
          fi
          curl -sS -X POST \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Content-Type: application/json" \
            "$SUPABASE_URL/functions/v1/notify-trial-ending" \
            | jq '.'
