name: Spec Guard
on:
  pull_request:
    branches: [ main, master ]

jobs:
  validate-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure required docs exist and run secret scan
        run: |
          test -f docs/high-level-plan.md || (echo "Missing docs/high-level-plan.md" && exit 1)
          test -f docs/implementation-todo.md || (echo "Missing docs/implementation-todo.md" && exit 1)
          test -f memory/constitution.md || (echo "Missing memory/constitution.md" && exit 1)
          test -d specs || (echo "Missing specs/ directory" && exit 1)
          count=$(ls -1 specs | wc -l)
          [ "$count" -gt 0 ] || (echo "No spec folders under specs/" && exit 1)
          npm ci
          npm run scan:secrets

      - name: Validate PR body includes phase, acceptance criteria, and Linear issue
        uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.pull_request && context.payload.pull_request.body) || '';
            const errors = [];
            if (!/Phase\s*:/i.test(body)) errors.push('PR body must include "Phase:"');
            if (!/Acceptance Criteria/i.test(body)) errors.push('PR body must include "Acceptance Criteria"');
            if (!/(Linear|Issue)/i.test(body)) errors.push('PR body should link a Linear issue (e.g., LG-123)');
            if (errors.length) {
              core.setFailed(errors.join('\n'));
            } else {
              core.info('Spec-guard validation passed.');
            }
